#!/usr/bin/env python
import os
output = open("output.sailing_mutask20_15", "w")
cmd = "./sailing  -f -a 0 -h 1 -s 0 50 random aot 100 100 0.5 50"
output.write("cmd=" + cmd + "\n")
output.close()
os.system(cmd + " >> output.sailing_mutask20_15")
