#!/usr/bin/env python
import os
output = open("output.sailing_mutask20_6", "w")
cmd = "./sailing  -f -a 0 -h 1 -s 0 50 random uct 5000 100 0"
output.write("cmd=" + cmd + "\n")
output.close()
os.system(cmd + " >> output.sailing_mutask20_6")
