#!/usr/bin/env python
import os
output = open("output.sailing_mutask20_25", "w")
cmd = "./sailing  -f -a 0 -h 1 -s 0 100 random uct 100 200 0"
output.write("cmd=" + cmd + "\n")
output.close()
os.system(cmd + " >> output.sailing_mutask20_25")
